name: Build PS5 Syslang

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. 拉取你的源码 (Checkout Code)
      uses: actions/checkout@v4

    - name: 2. 安装编译环境 (Install Compilers)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang lld make curl unzip vim-common

    - name: 3. 下载并部署 PS5 Payload SDK (Setup SDK)
      run: |
        curl -L -o ps5-payload-sdk.zip https://github.com/ps5-payload-dev/sdk/releases/download/v0.43/ps5-payload-sdk.zip
        sudo unzip -q ps5-payload-sdk.zip -d /opt/ps5-payload-sdk
        
    - name: 4. 开始编译插件 (Compile the Plugin)
      run: |
        export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
        make

    - name: 5. 导出编译成果 (Upload Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: ps5-syslang-build
        path: build/*.elf
